export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const FETCH_ORDERSMADE_START = "FETCH_ORDERSMADE_START";
export const FETCH_ORDERSMADE_SUCCESS = "FETCH_ORDERSMADE_SUCCESS";
export const FETCH_ORDERSMADE_FAIL = "FETCH_ORDERSMADE_FAIL";

export const FETCH_BUYPRODUCT_START = "FETCH_BUYPRODUCT_START";
export const FETCH_BUYPRODUCT_SUCCESS = "FETCH_BUYPRODUCT_SUCCESS";
export const FETCH_BUYPRODUCT_FAIL = "FETCH_BUYPRODUCT_FAIL";
